language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - pypy3
jobs:
  include:
    - env: TOXENV=flake8
    - env: TOXENV=mypy
    - env: TOXENV=check-manifest
    - env: TOXENV=check-python-versions
install:
  - pip install tox-travis
script:
  - tox
notifications:
  email: false
cache: pip
