# NB: this name is used in the status badge
name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 6"  # 5:00 UTC every Saturday

env:
  default_python: "3.9"

jobs:
  build:
    name: ${{ matrix.toxenv || matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "pypy3"
        toxenv: ["py"]
        include:
          - toxenv: flake8
          - toxenv: mypy
          - toxenv: check-manifest
          - toxenv: check-python-versions
          - toxenv: isort
          - toxenv: coverage

    steps:
      - name: Git clone
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version || env.default_python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version || env.default_python  }}

      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version || matrix.toxenv }}-${{ hashFiles('tox.ini', 'setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version || matrix.toxenv }}-
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U setuptools wheel
          python -m pip install -U tox

      - name: Run tests
        run: python -m tox -e ${{ matrix.toxenv || "py" }}
